env:
 - GHCVER=7.4.1
 - GHCVER=7.4.2
 - GHCVER=7.6.1
 - GHCVER=7.6.2
 - GHCVER=7.6.3
 - GHCVER=7.8.1
 - GHCVER=7.8.2
 - GHCVER=7.8.3
 - GHCVER=7.10.1
 - GHCVER=7.10.2
 - GHCVER=7.10.3
 - GHCVER=8.0.1
 - GHCVER=head

matrix:
  allow_failures:
    - env: GHCVER=8.0.1
    - env: GHCVER=head

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-1.24 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.24/bin:$PATH

install:
 - cabal --version
 - cabal update
 - cabal install   --enable-tests --enable-benchmarks --only-dependencies

script:
 - cabal configure --enable-tests --enable-benchmarks -v2
 - cabal build
 - cabal test
 - cabal check
 - cabal sdist
 - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal install "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi
